Implementing slider
virtual-labs/exp-heap-sort-iiith pull request #16
Opened 2022-06-27 09:09 UTC by Sr31bu

2022-07-02 18:42 UTC, shreyash-x requested changes

2022-07-02 18:42 UTC, shreyash-x commented on experiment/extract-min-operation/simulation/practice_extract.html
> +    <script src="static/animation/AnimationMain2.js"> </script>
Where is AnimationMain.js being used, I only see AnimationMain2.js  . Also give more relevant names to these files instead of calling them Main, something like the name of the experiment can be a good name for the js file.

2022-07-02 18:42 UTC, shreyash-x commented on experiment/extract-min-operation/simulation/static/animation/AnimationMain.js
> +var delay = 30;
Did you realize the relation between this value and actual delay? If so, add it in comments in that line only.

2022-07-02 18:42 UTC, shreyash-x commented on experiment/extract-min-operation/simulation/static/animation/AnimationMain.js
>  var timer;
Don't use var, use let instead.

2022-07-02 18:42 UTC, shreyash-x commented on experiment/heap-sort/simulation/practice_heapsort.html
> +    <script src="static/animation/AnimationMain2.js"> </script>
same here

2022-07-04 04:50 UTC, Sr31bu commented on experiment/extract-min-operation/simulation/practice_extract.html
> +    <script src="static/animation/AnimationMain2.js"> </script>
AnimationMain.js is being used by demo and the AnimationMain2.js is being used by practice.This is because the changes made to animationmain.js not apply to Animationmain2.js. I will however, change the file names.

2022-07-04 04:51 UTC, Sr31bu commented on experiment/extract-min-operation/simulation/static/animation/AnimationMain.js
> +var delay = 30;
No I did not actually but I will try to figure it out

2022-09-07 04:39 UTC, merged